export class AccountsFakeDb
{
    public static accounts = [
        {
            'id'      : '1',
            'accountName'    : 'Elvis Presley Fan Club',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '2',
            'accountName'    : 'TT Comapny',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
             'id'      : '3',
            'accountName'    : 'Bill Jones Company',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
       },
       {
            'id'      : '5',
            'accountName'    : 'Elvis Presley Fan Club',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '4',
            'accountName'    : 'TT Comapny',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '6',
            'accountName'    : 'Bill Jones Company',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
       },
       {
            'id'      : '7',
            'accountName'    : 'Elvis Presley Fan Club',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '8',
            'accountName'    : 'TT Comapny',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
             'id'      : '9',
            'accountName'    : 'Bill Jones Company',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
       },
       {
            'id'      : '10',
            'accountName'    : 'Elvis Presley Fan Club',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '12',
            'accountName'    : 'TT Comapny',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '13',
            'accountName'    : 'Bill Jones Company',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
       },
       {
            'id'      : '14',
            'accountName'    : 'Elvis Presley Fan Club',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
            'id'      : '22',
            'accountName'    : 'TT Comapny',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'San Diego',
            'billState': 'California',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
        },
        {
             'id'      : '23',
            'accountName'    : 'Bill Jones Company',
            'partnerType':  'Customer',
            'timezone': 'America/Chicago',
            'accountExtension': '110141',
            'website': 'http://wayneenterprises.com',
            'billAddress1': 'Wayne Manor',
            'billAddress2': '',
            'billingCity': 'Dallas',
            'billState': 'Texas',
            'billPostalcode': '92101',
            'billCountry': 'United States',
            'audit': '',
            'salesRep': 'Chris LaFave',
            'phone': '800.800.8000',
            'fax': '',
            'division': '',
            'accType': 'Active',
            'priorSalesRep': '',
            'shipAddress1': 'Wayne Manor',
            'shipAddress2': '',
            'shipCity': 'San Diego',
            'shipState': 'California',
            'shipPostalCode': '92101',
            'shipCountry': 'United States',
            'generalInfo': '',
            'logo'    : '/assets/images/logos/_logo.png',
            'created': '2018-04-19',
            'leadSource': 'Campaign',
            'industry': 'General Contractors Industrial',
            'shipAccount': '111',
            'shippingAccountType': '',
            'creditTerms': 'Net 30',
            'promoCode': '',
            'autoUpdate': '',
            'eqpVendor': '',
            'vendorPONote': '',
            'vendorProductNote': ''
       },
    ];
}
