export class ActivitiesFakeDb
{
    public static activities = [
        {
            id: '1',
            type: 'Meeting',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '2',
            type: 'Calls',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '3',
            type: 'Meeting',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '4',
            type: 'Task',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '5',
            type: 'Calls',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '6',
            type: 'Meeting',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '7',
            type: 'Task',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '8',
            type: 'Meeting',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher',
        },
        {
            id: '9',
            type: 'Meeting',
            subject: 'Check on new shirts',
            relatedTo: 'Opportunity',
            salesRep: 'Thomas Rios',
            dueDate: '2018-3-23',
            owner: 'Martin Fletcher'
        }
    ];
}
