export class ArtworksFakeDb
{
    public static designTypes = [
        'Colour Label', 'Data Upload', 'Decal', 'Die Cut', 'Digital Print',
        'Digital Sticker', 'Digital Transfer', 'Digital UV Label', 'DTG Printing',
        'Embroidery', 'Foil', 'For Branding Options Please Contact Us',
        'Full color expoxy dome', 'Full color print', 'Heat transfer',
        'Hot stamp', 'Kilin Fired', 'Label', 'Laser', 'Laser Engraving',
        'Logo', 'Metalic Print', 'Mould with color filled', 'Moulded', 'Other',
        'Pad Print', 'Resin', 'Resin Coated Print', 'Resin Dome', 'Rotary Engraving',
        'Rubber Printing', 'Screen Print', 'Screen Transfer', 'Sewing',
        'Spot color print', 'Sticker', 'Sublimation', 'Unbranded', 'UV Printing',
        'Wrap Print'
    ];

    public static artworks = [
        {
            id: '1',
            name: 'Artwork 1',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 1',
            designType: 'Colour Label',
            product: 'T-shirt',
            color: 'Red',
            status: 'Pending',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            image: 'assets/images/beach.jpg',
            priority: 'Low',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '2',
            name: 'Artwork 2',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 2',
            designType: 'Data Upload',
            product: 'T-shirt',
            color: 'Green',
            status: 'Assigned',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '3',
            name: 'Artwork 3',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 3',
            designType: 'Decal',
            product: 'T-shirt',
            color: 'Green',
            status: 'Assigned',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            image: 'assets/images/scrumboard/calendar.jpg',
            priority: 'High',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '4',
            name: 'Artwork 4',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 4',
            designType: 'Decal',
            product: 'T-shirt',
            color: 'Green',
            status: 'Waiting Customer Approval',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '5',
            name: 'Artwork 5',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 5',
            designType: 'Embroidery',
            product: 'T-shirt',
            color: 'Green',
            status: 'Waiting Customer Approval',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '6',
            name: 'Artwork 6',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 6',
            designType: 'Embroidery',
            product: 'T-shirt',
            color: 'Green',
            status: 'Waiting Distributor Approval',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            image: 'assets/images/scrumboard/header-1.jpg',
            priority: 'Low',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '7',
            name: 'Artwork 7',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 7',
            designType: 'Laser Engraving',
            product: 'T-shirt',
            color: 'Green',
            status: 'Waiting Distributor Approval',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '06/23/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '8',
            name: 'Artwork 8',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 8',
            designType: 'Foil',
            product: 'T-shirt',
            color: 'Green',
            status: 'Done',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '06/22/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '9',
            name: 'Artwork 9',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 9',
            designType: 'Foil',
            product: 'T-shirt',
            color: 'Green',
            status: 'Done',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '10',
            name: 'Artwork 10',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 10',
            designType: 'Foil',
            product: 'T-shirt',
            color: 'Green',
            status: 'Done',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '04/25/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '11',
            name: 'Artwork 11',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 11',
            designType: 'Sticker',
            product: 'T-shirt',
            color: 'Green',
            status: 'Done',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '06/21/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        },
        {
            id: '12',
            name: 'Artwork 12',
            designNumber: 'D001',
            customer: 'Implicit Web',
            order: 'Order 12',
            designType: 'Sticker',
            product: 'T-shirt',
            color: 'Green',
            status: 'Pending',
            assignee: 'James Lewis',
            descriptions: [],
            variations: [],
            priority: 'Low',
            due: '06/20/2018',
            notes: 'This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines. This is note. This shouldn\'t be more than 2 lines.'
        }
    ];
}
