export class CasesFakeDb
{
    public static cases = [
        {
            id: '1',
            number: '2',
            subject: 'Potential business',
            accountName: 'Implicit Web',
            priority: 'Medium',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '2',
            number: '3',
            subject: 'Sales Issue',
            accountName: 'BMW',
            priority: 'Medium',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '3',
            number: '21',
            subject: 'QA Issue',
            accountName: 'Implicit Web',
            priority: 'High',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '4',
            number: '32',
            subject: 'Projects Help',
            accountName: 'Apple',
            priority: 'Low',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '5',
            number: '12',
            subject: 'Sales Questions',
            accountName: 'Frontier',
            priority: 'Low',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '6',
            number: '7',
            subject: 'Adding Activity',
            accountName: 'Implicit Web',
            priority: 'Medium',
            status: 'Assigned',
            salesRep: 'QA Team',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '7',
            number: '27',
            subject: 'Follow Up',
            accountName: 'Atlas',
            priority: 'High',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
        {
            id: '8',
            number: '23',
            subject: 'New Ideas',
            accountName: 'Apple',
            priority: 'Low',
            status: 'Assigned',
            salesRep: 'Antera Support',
            dateCreated: '2018-3-23',
            type: 'Administration',
            description: 'Description ...',
            resolution: 'This is resolution to ...',
        },
    ];
}
