export class ContactsFakeDb
{
    public static contacts = [
        {
            id: '1',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19'
        },
        {
            id: '2',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19',
        },
        {
            id: '3',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19',
        },
        {
            id: '4',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19',
        },
        {
            id: '5',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19',
        },
        {
            id: '6',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19',
        },
        {
            id: '7',
            firstName: 'Abbott',
            lastName: 'Keitch',
            title: 'Digital Archivist',
            department: 'Sales',
            reportsTo: 'John Doe',
            shippingType: 'Shipping Type 1',
            shippingAcctNumber: '123123',
            salesRep: 'Jack Smith',
            phoneWork: '1234567890',
            phoneFax: '',
            description: 'Description ...',
            shipAddress1: '933 8th Street',
            shipAddress2: '',
            shipCity: 'Stamford',
            shipState: 'CT',
            shipPostalcode: '06902',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            email: 'abbott@withinpixels.com',
            dateCreated: '2017-4-19',
            dateModified: '2017-4-19',
        },
    ]
}
