export class InventoryFakeDb
{
    public static inventory = [
        {
            id: '1',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-10',
        },
        {
            id: '2',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-10',
        },
        {
            id: '3',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'green',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-10',
        },
        {
            id: '4',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '10',
            active: false,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-10',
        },
        {
            id: '5',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: false,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-10',
        },
        {
            id: '6',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-12',
        },
        {
            id: '7',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-13',
        },
        {
            id: '8',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-10',
        },
        {
            id: '9',
            name: 'Printed Dress',
            img: 'assets/images/ecommerce/product-image-placeholder.png',
            category: 'Dresses',
            price: '10.24',
            quantity: '3',
            active: true,
            sku: 'A445BV',
            size: 'm',
            color: 'red',
            site: '',
            bin: '',
            lastInsertDate: '2018-05-11',
        }
    ];
}
