export class LeadsFakeDb
{
    public static leads = [
        {
            'id'              : '1',
            'firstname'      : 'Bobby',
            'lastname'       : 'Charlton',
            'title'           : 'President',
            'referredBy'     : 'Mean Joe Green',
            'status'          : 'Converted',
            'accountName'    : 'TT Company',
            'phoneOffice'    : '214-555-1212',
            'email'           : 'rpeters@anterasoftware.com',
            'salesRep'       : 'Rick Peters',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Antera Support',
        },
        {
            'id'              : '2',
            'firstname'      : 'Davy',
            'lastname'       : 'Jones',
            'title'           : 'CEO',
            'referredBy'     : 'Will Turner',
            'status'          : 'Prospect',
            'accountName'    : 'Capital Ships',
            'phoneOffice'    : '249-144-1409',
            'email'           : 'djones@capitalships.com',
            'salesRep'       : 'Will Turner',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Will Turner',
        },
        {
            'id'              : '3',
            'firstname'      : 'Fitz',
            'lastname'       : 'Sprocket',
            'title'           : 'Supervisor',
            'referredBy'     : 'Mulgore Inc.',
            'status'          : 'Converted',
            'accountName'    : 'Venture Co.',
            'phoneOffice'    : '140-599-5923',
            'email'           : 'goldenboy@ventureco.eu',
            'salesRep'       : 'Amy Emilgund',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Mulgore Inc.',
        },
        {
            'id'              : '4',
            'firstname'      : 'Sammy',
            'lastname'       : 'Olsen',
            'title'           : 'Manager',
            'referredBy'     : 'Cassidy Kane',
            'status'          : 'Converted',
            'accountName'    : 'Apple Inc.',
            'phoneOffice'    : '989-245-5998',
            'email'           : 'solsen@anterasoftware.com',
            'salesRep'       : 'Cassidy Kane',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Kingston',
        },
        {
            'id'              : '5',
            'firstname'      : 'Ion',
            'lastname'       : 'Zur',
            'title'           : 'Producer',
            'referredBy'     : 'Logan Zachary',
            'status'          : 'New',
            'accountName'    : 'Lion\'s Arch Ltd.',
            'phoneOffice'    : '904-289-8114',
            'email'           : 'izur@warsguild.com',
            'salesRep'       : 'Logan Zachary',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Antera Support',
        },
        {
            'id'              : '6',
            'firstname'      : 'Remy',
            'lastname'       : 'LeBeau',
            'title'           : 'CFO',
            'referredBy'     : 'Charles Xavier',
            'status'          : 'Assigned',
            'accountName'    : 'TT Company',
            'phoneOffice'    : '214-555-1212',
            'email'           : 'remy@anterasoftware.com',
            'salesRep'       : 'Rick Peters',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Antera Support',
        },
        {
            'id'              : '7',
            'firstname'      : 'Rachel',
            'lastname'       : 'Focus',
            'title'           : 'Supervisor',
            'referredBy'     : 'Graham Eurich',
            'status'          : 'Converted',
            'accountName'    : 'Steel Ton Inc.',
            'phoneOffice'    : '885-275-5757',
            'email'           : 'rfocus@steelton.biz',
            'salesRep'       : 'Rick Peters',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Graham Eurich',
        },
        {
            'id'              : '8',
            'firstname'      : 'Thomas',
            'lastname'       : 'Blitzkreig',
            'title'           : 'CTO',
            'referredBy'     : 'Ophelia Rushmore',
            'status'          : 'New',
            'accountName'    : 'Chargers',
            'phoneOffice'    : '741-587-8442',
            'email'           : 'kreigersan@chargers.com',
            'salesRep'       : 'Cage Sampson',
            'dateCreated'    : '04-19-2018 03:43pm',
            'createdBy'      : 'Ophelia Rushmore',
        }
    ];
}
