export class LocationsFakeDb
{
    public static locations = [
        {
            id: '1',
            companyName: 'Apple Inc.',
            contact: 'Marcus Lewis',
            deliveryContact: 'Dan Marino',
            salesRep: '',
            locationName: '',
            phone: '214-555-1212',
            type: 'Customer',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Royse City',
            shipState: 'Texas',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '2',
            companyName: 'Atlas',
            contact: 'Marcus Lewis',
            deliveryContact: 'Connor McHale',
            salesRep: '',
            locationName: '',
            phone: '914-886-5950',
            type: 'Vendor',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Santa Monica',
            shipState: 'California',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '3',
            companyName: 'Bespin Mining',
            contact: 'Marcus Lewis',
            deliveryContact: 'Lando Calrissian',
            salesRep: '',
            locationName: '',
            phone: '414-204-0026',
            type: 'Customer',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Cloud City',
            shipState: 'Bespin',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '4',
            companyName: 'Diamond Lasers',
            contact: 'Marcus Lewis',
            deliveryContact: 'Richard King',
            salesRep: '',
            locationName: '',
            phone: '519-250-1112',
            type: 'Vendor',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'St Louis',
            shipState: 'Missouri',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '5',
            companyName: 'Line Walkers Inc.',
            contact: 'Marcus Lewis',
            deliveryContact: 'Johnathan Cash',
            salesRep: '',
            locationName: '',
            phone: '141-222-5190',
            type: 'Customer',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Kingsland',
            shipState: 'Arkansas',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '6',
            companyName: 'Cascade Enterprises',
            contact: 'Marcus Lewis',
            deliveryContact: 'Daphne Burch',
            salesRep: '',
            locationName: '',
            phone: '842-142-5151',
            type: 'Customer',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Seattle',
            shipState: 'Washington',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '7',
            companyName: 'Creative Co.',
            contact: 'Marcus Lewis',
            deliveryContact: 'Tammy Jackson',
            salesRep: '',
            locationName: '',
            phone: '315-222-5192',
            type: 'Vendor',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Miami',
            shipState: 'Floria',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '8',
            companyName: 'The News Inc.',
            contact: 'Marcus Lewis',
            deliveryContact: 'Huey Lewis',
            salesRep: '',
            locationName: '',
            phone: '555-145-6642',
            type: 'Vendor',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'Dallas',
            shipState: 'Texas',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
        {
            id: '9',
            companyName: 'BMW',
            contact: 'Marcus Lewis',
            deliveryContact: 'Brian Fantana',
            salesRep: '',
            locationName: '',
            phone: '482-145-9292',
            type: 'Customer',
            fax: '',
            shipAddress1: '',
            shipAddress2: '',
            shipCity: 'San Diego',
            shipState: 'California',
            shipPostalcode: '',
            shipCountry: '',
            billAddress1: '',
            billAddress2: '',
            billCity: '',
            billState: '',
            billPostalcode: '',
            billCountry: '',
            description: '',
            accounts: '',
        },
    ];
}
