export class OpportunitiesFakeDb
{
    public static opportunities = [
        {
            'id'              : '1',
            'name'            : 'Golf Tourament',
            'type'            : 'Existing Customer',
            'businessType'    : 'Head Honcho',
            'amount'          : '$25,000.00',
            'salesStage'      : 'Final Review',
            'probability'     : 'TT Company',
            'closeDate'       : '02-28-2017',
            'eventDate'       : '02-28-2017',
            'inHandsDate'     : 'Rick Peters',
            'description'     : 'Wanting Polo for a charity Golf Tournament . Wanting Polo for a charity Golf Tournament .Wanting Polo for a charity Golf Tournament .Wanting Polo for a charity Golf Tournament ',
            'accountName'     : 'Antera',
            'contactName'     : 'Trevor Landry',
            'leadSource'      : 'Word of mouth',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : '',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '01-25-2017',
            'dateModified'    : ''
        },
        {
            'id'              : '2',
            'name'            : '151: Sage Transfer',
            'type'            : 'New Customer',
            'businessType'    : 'Apparel',
            'amount'          : '$12,500.00',
            'salesStage'      : 'Search Items',
            'probability'     : '40',
            'closeDate'       : '09-30-2015',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : '',
            'accountName'     : 'BMW USA',
            'contactName'     : 'Rick Peters',
            'leadSource'      : 'Word of mouth',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : '',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '09-21-2015',
            'dateModified'    : ''
        },
        {
            'id'              : '3',
            'name'            : '146: Shirts for Softball Leage',
            'type'            : 'New Customer',
            'businessType'    : 'Apparel',
            'amount'          : '$5,000.00',
            'salesStage'      : 'Prospecting',
            'probability'     : '10',
            'closeDate'       : '09-18-2017',
            'eventDate'       : '09-25-2017',
            'inHandsDate'     : '02-18-2018',
            'description'     : '',
            'accountName'     : 'Antera Software USA',
            'contactName'     : 'John Smith',
            'leadSource'      : 'Cold Call',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : 'Antera Support',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '09-04-2017',
            'dateModified'    : ''
        },
        {
            'id'              : '4',
            'name'            : '114: 250 Beach Balls',
            'type'            : 'New Customer',
            'businessType'    : 'Promotional',
            'amount'          : '$3,400.00',
            'salesStage'      : 'Initial Quoting',
            'probability'     : '20',
            'closeDate'       : '06-17-2017',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : '',
            'accountName'     : 'Metro Promotional',
            'contactName'     : 'Trevor Landry',
            'leadSource'      : 'Self Generate',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : '',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '06-15-2017',
            'dateModified'    : ''
        },
        {
            'id'              : '5',
            'name'            : '54: New Party',
            'type'            : '',
            'businessType'    : '',
            'amount'          : '$10,000.00',
            'salesStage'      : 'Proposal/Price Quote',
            'probability'     : '30',
            'closeDate'       : '01-22-2015',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : '',
            'accountName'     : 'Unforgiven',
            'contactName'     : 'Clint Eastwood',
            'leadSource'      : 'Web Site',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : '',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '01-13-2015',
            'dateModified'    : ''
        },
        {
            'id'              : '6',
            'name'            : '118: Sage Transfer',
            'type'            : 'New Customer',
            'businessType'    : '',
            'amount'          : '$22,000.00',
            'salesStage'      : 'Prospecting',
            'probability'     : '10',
            'closeDate'       : '06-26-2015',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : '',
            'accountName'     : 'Searchers',
            'contactName'     : 'John Wayne',
            'leadSource'      : 'Web Site',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : 'Daniel Ostertag',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '01-25-2017',
            'dateModified'    : '01-03-2018'
        },
        {
            'id'              : '7',
            'name'            : '113: Quote# 2356',
            'type'            : 'New Customer',
            'businessType'    : '',
            'amount'          : '$2,000.00',
            'salesStage'      : 'Initial Quoting',
            'probability'     : '20',
            'closeDate'       : '06-30-2015',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : '',
            'accountName'     : 'BMW USA',
            'contactName'     : 'Duane Mailey',
            'leadSource'      : 'Web Site',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : 'Jody Cunningham',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '06-11-201',
            'dateModified'    : ''
        },
        {
            'id'              : '8',
            'name'            : 'Golf Tourament',
            'type'            : 'New Customer',
            'businessType'    : 'Head Honcho',
            'amount'          : '$25,000.00',
            'salesStage'      : 'Final Review',
            'probability'     : 'TT Company',
            'closeDate'       : '02-28-2017',
            'eventDate'       : '02-28-2017',
            'inHandsDate'     : 'Rick Peters',
            'description'     : 'Wanting Polo for a charity Golf Tournament . Wanting Polo for a charity Golf Tournament .Wanting Polo for a charity Golf Tournament .Wanting Polo for a charity Golf Tournament ',
            'accountName'     : 'Antera',
            'contactName'     : 'Trevor Landry',
            'leadSource'      : 'Word of mouth',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : '',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '01-25-2017',
            'dateModified'    : ''
        },
        {
            'id'              : '9',
            'name'            : '73: Sage Transfer',
            'type'            : 'New Customer',
            'businessType'    : 'Head Honcho',
            'amount'          : '$10,000.00',
            'salesStage'      : 'Proposal/Price Quote',
            'probability'     : '30',
            'closeDate'       : '03-15-2015',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : 'Wanting Polo for a charity Golf Tournament . Wanting Polo for a charity Golf Tournament .Wanting Polo for a charity Golf Tournament .Wanting Polo for a charity Golf Tournament ',
            'accountName'     : 'Unforgiven',
            'contactName'     : 'Clint Eastwood',
            'leadSource'      : 'Web Site',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : 'Albert Einstein',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '02-17-2015',
            'dateModified'    : ''
        },
        {
            'id'              : '10',
            'name'            : '74: Baby Shower',
            'type'            : 'New Customer',
            'businessType'    : '',
            'amount'          : '$3,000.00',
            'salesStage'      : 'Search Items',
            'probability'     : '25',
            'closeDate'       : '02-27-2015',
            'eventDate'       : '06-06-2018',
            'inHandsDate'     : '06-06-2018',
            'description'     : '',
            'accountName'     : 'Searchers',
            'contactName'     : 'John Wayne',
            'leadSource'      : 'Web Site',
            'campaign'        : '',
            'nextStep'        : '',
            'assigned_to'     : 'Albert Einstein',
            'budget'          : '',
            'location'        : '',
            'dateCreated'     : '02-18-2015',
            'dateModified'    : ''
        }
    ];
}
