export class WebstoreFakeDb
{
    public static webstore = [
        {
            id: '1',
            clientName: 'Apple',
            hostName: 'apple.anterastores.com',
            points: '1,000.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 1',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '2',
            clientName: 'BMW',
            hostName: 'bmw.anterastores.com',
            points: '181.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 1',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '3',
            clientName: 'Apple',
            hostName: 'golfstream.anterastores.com',
            points: '911.0',
            distributor: 'Roberts',
            enabled: false,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '4',
            clientName: 'BMW',
            hostName: 'johndeere.anterastores.com',
            points: '158.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 1',
            salesPerson: 'Lawrenece Collins',
            currency: 'EUR',
            css: '.webstore { color: green; }',
        },
        {
            id: '5',
            clientName: 'Brooks Running',
            hostName: 'brooksrunning.anterastores.com',
            points: '123.0',
            distributor: 'Roberts',
            enabled: false,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '6',
            clientName: 'Apple',
            hostName: 'atlas.anterastores.com',
            points: '2,592.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test1',
            orderType: 'Order Type 3',
            salesPerson: 'Lawrenece Collins',
            currency: 'EUR',
            css: '.webstore { color: green; }',
        },
        {
            id: '7',
            clientName: 'Brooks Running',
            hostName: 'prodcuts.anterastores.com',
            points: '1,702.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 1',
            salesPerson: 'Lawrenece Collins',
            currency: 'GBP',
            css: '.webstore { color: green; }',
        },
        {
            id: '8',
            clientName: 'Atlas',
            hostName: 'rolex.anterastores.com',
            points: '230.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '9',
            clientName: 'Travel',
            hostName: 'protravel.anterastores.com',
            points: '10.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '10',
            clientName: 'Brooks Running',
            hostName: 'printuidemo.anterastores.com',
            points: '110.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '11',
            clientName: 'Brooks Running',
            hostName: 'elevate.anterastores.com',
            points: '102.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
        {
            id: '12',
            clientName: 'SnowEx',
            hostName: 'snowexgear.anterastores.com',
            points: '1,240.0',
            distributor: 'Roberts',
            enabled: true,
            logo: '',
            crmUrl: 'https://crm.example.com',
            crmAccount: 'crm-test',
            orderType: 'Order Type 2',
            salesPerson: 'Lawrenece Collins',
            currency: 'USD',
            css: '.webstore { color: green; }',
        },
    ];
}
