apiVersion: v1
kind: Service
metadata:
  name: clients-__CI_ENVIRONMENT_SLUG__-__APP__
  labels:
    app: __APP__
    location: __CI_ENVIRONMENT_SLUG__
spec:
  ports:
  - port: __PORT__
  selector:
    location: __CI_ENVIRONMENT_SLUG__
    app: __APP__
